Feature/pfm 21 create groups
uktrade/digital-workspace-v2 pull request #175
Opened 2022-02-09 10:53 UTC by Luisella21

Create groups.
Add permission checks where needed.
Create tests.

2022-02-09 12:04 UTC, rossmiller requested changes
Looks good but we now need to remove the edit_sso_id

2022-02-09 12:04 UTC, rossmiller commented on peoplefinder/management/commands/create_people_finder_groups.py
> +    "edit_sso_id",
Please remove edit_sso_id.

2022-02-09 12:04 UTC, rossmiller commented on peoplefinder/migrations/0057_auto_20220207_1206.py
> +            options={'permissions': (('edit_profile', 'Edit profile'), ('delete_profile', 'Delete profile'), ('edit_sso_id', 'Edit SSO ID'))},
Remove edit_sso_id

2022-02-09 12:04 UTC, rossmiller commented on peoplefinder/models.py
> +            ("edit_sso_id", "Edit SSO ID"),
Remove edit_sso_id

2022-02-09 12:04 UTC, rossmiller commented on pii-ner-exclude.txt
> +edit_sso_id"
Remove edit_sso_id"

2022-02-09 12:04 UTC, rossmiller commented on peoplefinder/test/views/test_profile_views.py
> +
Remove line break

2022-02-09 14:16 UTC, Luisella21 commented on peoplefinder/test/views/test_profile_views.py
> +
Done.

2022-02-15 18:24 UTC, rossmiller approved these changes
LGTM!

2022-02-15 18:25 UTC, merged