Adding delete profile function
uktrade/digital-workspace-v2 pull request #183
Opened 2022-03-04 12:28 UTC by rossmiller

2022-03-15 11:02 UTC, rossmiller commented on pii-secret-exclude.txt
> +peoplefinder/management/commands/create_test_users.py
Don't add these unless you have to

2022-03-15 11:05 UTC, rossmiller commented on peoplefinder/management/commands/create_test_users.py
> +        self.stdout.write(self.style.SUCCESS("Job completed successfully"))
Confirm the email address in the SUCCESS output: "Jane Doe (jane.doe@test.com) was created" or similar

2022-03-15 12:48 UTC, rossmiller commented on peoplefinder/management/commands/setup_v2_user.py
> +    help = """Create user profiles for local testing purposes"""
Make chosen user use People Finder V2

2022-03-15 12:48 UTC, rossmiller commented on peoplefinder/management/commands/setup_v2_user.py
> +            raise CommandError('User with email "%s" does not exist' % email)
Let's use a new Python format string

2022-03-15 12:48 UTC, rossmiller commented on peoplefinder/management/commands/setup_v2_user.py
> +            self.style.SUCCESS("User profile set to use PF v2 successfully")
Add user name and email to output

2022-03-15 12:48 UTC, rossmiller commented on peoplefinder/services/person.py
> +You can update any profile on Digital Workspace. Find out more at: https://workspace.trade.gov.uk/working-at-dit/policies-and-guidance/using-people-finder/
Let's reduce this string length

2022-03-15 12:48 UTC, rossmiller commented on peoplefinder/services/person.py
> +            person: The person behind the profile.
Arg list needs request

2022-03-15 12:48 UTC, rossmiller commented on peoplefinder/services/person.py
>          """A method to be called after a profile has been deleted.
Remove this line.

2022-03-15 12:48 UTC, rossmiller commented on peoplefinder/services/person.py
>          Please don't forget to call method this unless you need to bypass it.
Reword needed:

"This is the main hook for calling out to other processes which need to happen after a profile has been deleted. Please don't forget to call this method unless you need to bypass it."

2022-03-15 12:48 UTC, rossmiller commented on peoplefinder/services/person.py
>              person: The person behind the profile.
Needs request arg

2022-03-15 12:48 UTC, rossmiller commented on peoplefinder/services/person.py
> +NOTIFY_ABOUT_DELETION_LOG_MESSAGE = """Hello {profile_name},
Remove this variable.

2022-03-15 12:48 UTC, rossmiller commented on peoplefinder/services/person.py
> +            settings.PROFILE_DELETED_EMAIL_TEMPLATE_ID,
Needs email_address and template_id kwargs.
We also need the personalisation kwarg with the correct values assigned. 

send_email_notification(
            email=person.user.email,
            template_id=settings.PROFILE_DELETED_EMAIL_TEMPLATE_ID,
            personalisation=context,
)

2022-03-15 12:48 UTC, rossmiller commented on peoplefinder/test/views/test_delete_profile_views.py
> +    # Find delete 'button'
Find button (the function is not specifically about a delete button)

2022-03-16 10:51 UTC, SamDudley requested changes

2022-03-16 10:51 UTC, SamDudley commented on peoplefinder/management/commands/setup_v2_user.py
> +        user.user_permissions.add(Permission.objects.get(codename="edit_profile"))
These permissions have been removed as they duplicated existing permissions.

This logic should use the new `PersonService.update_groups_and_permissions` static method.

2022-03-16 10:51 UTC, SamDudley commented on peoplefinder/services/person.py
> +        person.became_inactive = datetime.now()
You should use Django's `timezone.now()` for a timezone aware datetime. Please read the following:

https://docs.djangoproject.com/en/4.0/topics/i18n/timezones/#naive-and-aware-datetime-objects

2022-03-16 10:51 UTC, SamDudley commented on peoplefinder/services/person.py
> +    assert len(Person._meta.get_fields()) == 39, (
Don't forget to rebase when you are finished and check this number is still valid. I think I've incremented it so it might be different.

2022-03-16 10:51 UTC, SamDudley commented on peoplefinder/templates/peoplefinder/profile.html
> +                {% if perms.peoplefinder.delete_profile and request.user != profile.user %}
As discussed offline, these permissions have been removed in favour of the builtin ones.

2022-03-16 10:51 UTC, SamDudley commented on peoplefinder/templates/peoplefinder/profile.html
> +                    <form action="{% url 'profile-delete' profile.slug %}" method="post" onsubmit="javascript:return confirm('Are you sure? This cannot be undone.')">
This needs a wider discussion, but, this can be undone now can't it? if we have implemented this as a soft delete.

2022-03-16 10:51 UTC, SamDudley commented on peoplefinder/test/views/test_delete_profile_views.py
> +    delete_profile_perm = Permission.objects.get(codename="delete_profile")
Same again with this permission.

2022-03-16 10:51 UTC, SamDudley commented on peoplefinder/test/views/test_delete_profile_views.py
> +    delete_profile_perm = Permission.objects.get(codename="delete_profile")
Same again with this permission.

2022-03-16 10:51 UTC, SamDudley commented on peoplefinder/test/views/test_delete_profile_views.py
> +    )
`bool` is unnecessary

2022-03-16 10:51 UTC, SamDudley commented on peoplefinder/test/views/test_profile_views.py
> +    perm = Permission.objects.get(codename="edit_profile")
Old permission

2022-03-16 10:51 UTC, SamDudley commented on peoplefinder/test/views/test_profile_views.py
> +    response = state.client.post(view_url, payload)
Why not just build the payload as a dict and pass it straight to `post`? The use of `ProfileForm` here feels unnecessary.

https://docs.djangoproject.com/en/4.0/topics/testing/tools/#django.test.Client.post

2022-03-16 15:50 UTC, nahmed99 commented on peoplefinder/templates/peoplefinder/profile.html
> +                    <form action="{% url 'profile-delete' profile.slug %}" method="post" onsubmit="javascript:return confirm('Are you sure? This cannot be undone.')">
Yes, potentially it could be - directly on the db.

2022-03-16 16:01 UTC, nahmed99 commented on peoplefinder/test/views/test_profile_views.py
> +    response = state.client.post(view_url, payload)
I think this was due to the number of fields (and associated data) that we used from state.person. @rossmiller - any other/further reasons, or should we use a straight dict as Sam suggests?

2022-03-17 08:18 UTC, SamDudley commented on peoplefinder/services/person.py
> +        if deleted_by == person:
Here you are comparing a `Person` to a `User`. You need to get the user of the person and then compare.

2022-03-22 09:22 UTC, rossmiller commented on peoplefinder/test/views/test_profile_views.py
> +    response = state.client.post(view_url, payload)
@SamDudley this is because of the number of items required in the form. This also protects the test from changes to the structure of the form.

2022-03-24 11:57 UTC, merged