Sentry issue 71022: add sanitize function for search queries
uktrade/digital-workspace-v2 pull request #316
Opened 2023-02-15 14:27 UTC by marcelkornblum

People entering various non-URL-safe chars break the search function

https://sentry.ci.uktrade.digital/organizations/dit/issues/71022/?project=161

This PR removes those characters from the query silently, allowing for more likely matching.

2023-02-16 09:13 UTC, SamDudley requested changes

2023-02-16 09:13 UTC, SamDudley commented on search/search.py
> +    if query is None:
If `query` can be `None` then the type annotation should be `query: Optional[str]`.

2023-02-16 09:13 UTC, SamDudley commented on search/search.py
> +    return re.sub('[^a-zA-Z0-9-.~_\s]', "", query)
I think there will be issues with this if people want to search using accented characters?

2023-02-16 09:54 UTC, marcelkornblum commented on search/search.py
> +    return re.sub('[^a-zA-Z0-9-.~_\s]', "", query)
good call. do we know what the ES tokenisation does - does it retain those or convert them to ascii?

or should i investigate?

2023-02-21 09:13 UTC, SamDudley requested changes

2023-02-21 09:13 UTC, SamDudley commented on search/search.py
> +            cleaned_match = f"'{cleaned_match}'"
Should the quotes be double or singles? Could the quotes match what the user put?

2023-02-21 09:13 UTC, SamDudley commented on search/search.py
> +def sanitize_search_query(query: Optional[str] = None) -> str:
I think this kind of change warrants a set of test cases to ensure the behaviour works as expected and does not regress if we need to modify it further.

2023-02-21 09:41 UTC, marcelkornblum commented on search/search.py
> +            cleaned_match = f"'{cleaned_match}'"
AFAIK OpenSearch doesn't care; I thought I'd make them consistent to the search as it doesn't affect the user at all

2023-02-21 10:44 UTC, marcelkornblum commented on search/search.py
> +def sanitize_search_query(query: Optional[str] = None) -> str:
tests added - and a good thing as well, I realised I was stripping rather than asciifolding 🤦

2023-02-21 10:49 UTC, SamDudley approved these changes

2023-02-21 10:49 UTC, SamDudley commented on search/test/test_search.py
> +class TestSearchUtils(TestCase):
Suggestion: refactor using pytest's parametrize feature

https://docs.pytest.org/en/6.2.x/parametrize.html

example here https://github.com/uktrade/digital-workspace-v2/blob/9afb541512bd48d43a0c04d8bb3f21ae4e55b022/peoplefinder/test/services/test_audit_log.py#L94

2023-02-21 11:32 UTC, merged