WCM-229 Begin work
uktrade/digital-workspace-v2 pull request #5
Opened 2021-02-17 16:45 UTC by SamDudley

2021-02-18 13:01 UTC, SamDudley commented on content/management/commands/create_groups.py
> +        #     # FIXME: do we need to add newscategory still?
Thoughts?

2021-02-18 15:09 UTC, rossmiller commented on content/management/commands/create_groups.py
> +        #     # FIXME: do we need to add newscategory still?
Yes, news categories should be added.

2021-02-18 15:10 UTC, rossmiller requested changes
I've had a chat with the news team and they want to remove the concept of a news editor (they only need moderator).

2021-02-22 14:03 UTC, rossmiller approved these changes
LGTM!

2021-02-23 11:14 UTC, merged