DWPF-778 Show bad results message
uktrade/digital-workspace-v2 pull request #506
Opened 2023-11-14 14:29 UTC by nicopicchio

2023-11-14 14:35 UTC, CamLamb commented on src/search/search.py
> +        self.annotate_score = True
`self.annotate_score` is no longer used anywhere

2023-11-14 14:38 UTC, CamLamb commented on src/search/utils.py
> +def query_has_bad_results(query, category, pinned_results, search_results):
Can you add a comment to explain the purpose of this method?

2023-11-14 14:38 UTC, CamLamb commented on src/search/utils.py
> +def get_bad_score_threshold(query, category):
Can you add a comment to explain the purpose of this method?

2023-11-14 14:43 UTC, marcelkornblum requested changes
Good as far as it goes, but there are a few bits missing from what the ticket needs (see specific comments)

2023-11-14 14:43 UTC, marcelkornblum commented on src/search/templates/search/partials/search_results_category.html
> +    {% if show_bad_results_message %}<h1>These results might not be what you are looking for</h1>{% endif %}
I think we need a few different versions of this copy depending on other criteria - are there lots of results or only a few? which type of search are we on?

2023-11-14 14:43 UTC, marcelkornblum commented on src/search/utils.py
> +def query_has_bad_results(query, category, pinned_results, search_results):
could we rename this to be more on-the-nose please? maybe `only_has_bad_results` or `has_no_good_results` or something?

2023-11-14 14:43 UTC, marcelkornblum commented on src/search/utils.py
> +import statistics
i tihnk this is overkill for what we want to do

2023-11-14 14:43 UTC, marcelkornblum commented on src/search/utils.py
> +    bad_score_threshold_multiplier = 1
this should be extracted to an easier-to-change setting. I tihnk an ENV var in settings is probably best.

2023-11-14 14:43 UTC, marcelkornblum commented on src/search/utils.py
> +    return statistics.median(boost_values) * bad_score_threshold_multiplier
i am not convinced median is right - more like the 70th percentile maybe, just as the curve gets steeper? either way I don't think we need the stats package here; all we're doing is choosing the nth value where N / total = {our percentile}. so if we want median we total the number of boosts, halve the total to get N and select the boost at position N in the list.

2023-11-14 14:43 UTC, marcelkornblum commented on src/search/utils.py
> +def get_query_info(fields, field, mapping, suffix_map):
these copied-acrss functions would ideally get tidied up, they're such a mess. not going to mind if you don't though :)

2023-11-14 14:47 UTC, nicopicchio commented on src/search/templates/search/partials/search_results_category.html
> +    {% if show_bad_results_message %}<h1>These results might not be what you are looking for</h1>{% endif %}
we do but I am waiting for Bobby to come up with a final copy. initially it was `hello world`, I've only changed it to give a more meaningful message before opening this PR

2023-11-14 14:48 UTC, marcelkornblum commented on src/search/templates/search/partials/search_results_category.html
> +    {% if show_bad_results_message %}<h1>These results might not be what you are looking for</h1>{% endif %}
sure, but it also needs to be more than one message depending on other factors - so those factors ought to make an appearance here

2023-11-14 14:54 UTC, nicopicchio commented on src/search/utils.py
> +import statistics
ok, what do you suggest instead?

2023-11-14 14:54 UTC, marcelkornblum commented on src/search/utils.py
> +import statistics
commented below

2023-11-14 15:19 UTC, nicopicchio commented on src/search/utils.py
> +def query_has_bad_results(query, category, pinned_results, search_results):
renamed to `has_only_bad_results`

2023-11-15 10:25 UTC, nicopicchio commented on src/search/utils.py
> +    bad_score_threshold_multiplier = 1
done

2023-11-23 12:29 UTC, marcelkornblum reviewed
just one last thing please - otherwise looking fantastic

2023-11-23 12:29 UTC, marcelkornblum commented on src/search/templatetags/search.py
> +    show_bad_threshold_message=True,
could we rationalise the variables `show_bad_threshold_message` and `show_bad_results_message` across the whole codebase please? I can't see a reason to have them being different and it'd be easier to understand the code if they were named the same (assuming they are in fact doing the same thing)

2023-11-23 12:36 UTC, nicopicchio commented on src/search/templatetags/search.py
> +    show_bad_threshold_message=True,
renamed `show_bad_results_message`

2023-11-23 16:28 UTC, merged